// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Data_Loading_Tool.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Data_Loading_Tool.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class CreateViewTemplate : CreateViewTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n\r\ncreate view [");
            
            #line 9 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ViewName));
            
            #line default
            #line hidden
            this.Write("]\r\nas\r\n\r\nselect \r\n");
            
            #line 13 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"

	foreach(ViewColumnModel column in Model.Columns)
	{

            
            #line default
            #line hidden
            this.Write("\tISNULL([");
            
            #line 17 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 17 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("], 0) as [");
            
            #line 17 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("], \r\n");
            
            #line 18 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"

	}
	String geogColumn = "";
	String geogAlias = "";

	switch(Model.SelectedGeographyType) 
	{
		case 1:
			geogColumn = "UPRN";
			geogAlias = "UPRN";
			break;
		case 2:
			geogColumn = "Postcode";
			geogAlias = "Postcode";
			break;
		case 3:
			geogColumn = "LsoaName";
			geogAlias = "LSOA";
			break;
		case 4:
			geogColumn = "WardName";
			geogAlias = "Ward";
			break;
		case 5:
			geogColumn = "MsoaName";
			geogAlias = "MSOA";
			break;
		case 6:
			geogColumn = "CouncilArea";
			geogAlias = "Whole Council Area";
			break;
	}

            
            #line default
            #line hidden
            this.Write("\t\r\n\tGeog.");
            
            #line 51 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(geogColumn));
            
            #line default
            #line hidden
            this.Write(" as [");
            
            #line 51 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(geogAlias));
            
            #line default
            #line hidden
            this.Write("]\r\nfrom\r\n(\r\nselect \r\n\tG.");
            
            #line 55 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(geogColumn));
            
            #line default
            #line hidden
            this.Write("\r\nfrom \r\nGeography G\r\nwhere G.GeographyTypeID = ");
            
            #line 58 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.SelectedGeographyType));
            
            #line default
            #line hidden
            this.Write("\r\n) Geog\r\n\r\n");
            
            #line 61 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"

	foreach(ViewColumnModel column in Model.Columns)
	{

            
            #line default
            #line hidden
            this.Write("\tleft outer join \r\n\t(\r\n\t\tselect \r\n\t\t\tG.");
            
            #line 68 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(geogColumn));
            
            #line default
            #line hidden
            this.Write(", sum(I.Value) as [");
            
            #line 68 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("]\r\n\t\tfrom \r\n\t\t\tMeasureInstance I\r\n\t\tinner join \r\n\t\t\tGeography G\r\n\t\ton \r\n\t\t\tI.Geog" +
                    "raphyID = G.GeographyID\r\n\t\twhere\r\n\t\t\tI.DimensionSetCombinationID = ");
            
            #line 76 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SelectedDimensionValueID));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tand \r\n\t\t\tI.MeasureBreakdownID = ");
            
            #line 78 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SelectedMeasureBreakdownID));
            
            #line default
            #line hidden
            this.Write("\r\n\t\tgroup by \r\n\t\t\tG.");
            
            #line 80 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(geogColumn));
            
            #line default
            #line hidden
            this.Write("\r\n\t) as [");
            
            #line 81 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("]\r\n\ton [");
            
            #line 82 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("].");
            
            #line 82 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(geogColumn));
            
            #line default
            #line hidden
            this.Write(" = Geog.");
            
            #line 82 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(geogColumn));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 83 "C:\Development\Ben B\Code\Geographical Needs\Data Loading Tool\Templates\CreateViewTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class CreateViewTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
