USE [master]
GO

/****** Object:  Database [Geographical Needs]    Script Date: 01/07/2015 09:58:07 ******/
CREATE DATABASE [Geographical Needs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Geographical Needs', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Geographical Needs.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Geographical Needs_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Geographical Needs_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Geographical Needs] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Geographical Needs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Geographical Needs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Geographical Needs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Geographical Needs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Geographical Needs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Geographical Needs] SET ARITHABORT OFF 
GO

ALTER DATABASE [Geographical Needs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Geographical Needs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Geographical Needs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Geographical Needs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Geographical Needs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Geographical Needs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Geographical Needs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Geographical Needs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Geographical Needs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Geographical Needs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Geographical Needs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Geographical Needs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Geographical Needs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Geographical Needs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Geographical Needs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Geographical Needs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Geographical Needs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Geographical Needs] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Geographical Needs] SET  MULTI_USER 
GO

ALTER DATABASE [Geographical Needs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Geographical Needs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Geographical Needs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Geographical Needs] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Geographical Needs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Geographical Needs] SET  READ_WRITE 
GO


