//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessServices.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataView
    {
        public DataView()
        {
            this.DataViewColumns = new HashSet<DataViewColumn>();
        }
    
        public int DataViewID { get; set; }
        public string ViewName { get; set; }
    
        public virtual ICollection<DataViewColumn> DataViewColumns { get; set; }
    }
}
