//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimensionSetCombination
    {
        public DimensionSetCombination()
        {
            this.DimensionSetCombinationMembers = new HashSet<DimensionSetCombinationMember>();
            this.MeasureInstances = new HashSet<MeasureInstance>();
        }
    
        public int DimensionSetCombinationID { get; set; }
        public int DimensionSetID { get; set; }
        public string DimensionSetCombinationName { get; set; }
    
        public virtual DimensionSet DimensionSet { get; set; }
        public virtual ICollection<DimensionSetCombinationMember> DimensionSetCombinationMembers { get; set; }
        public virtual ICollection<MeasureInstance> MeasureInstances { get; set; }
    }
}
