//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimensionSet
    {
        public DimensionSet()
        {
            this.DimensionSetMembers = new HashSet<DimensionSetMember>();
            this.DimensionSetCombinations = new HashSet<DimensionSetCombination>();
            this.MeasureBreakdowns = new HashSet<MeasureBreakdown>();
        }
    
        public int DimensionSetID { get; set; }
        public string DimensionSetName { get; set; }
    
        public virtual ICollection<DimensionSetMember> DimensionSetMembers { get; set; }
        public virtual ICollection<DimensionSetCombination> DimensionSetCombinations { get; set; }
        public virtual ICollection<MeasureBreakdown> MeasureBreakdowns { get; set; }
    }
}
