//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactInstance
    {
        public int FactInstanceID { get; set; }
        public int FactDimensionSetID { get; set; }
        public Nullable<int> LsoaID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public int Value { get; set; }
    
        public virtual FactDimensionSet FactDimensionSet { get; set; }
        public virtual LSOA LSOA { get; set; }
        public virtual Property Property { get; set; }
    }
}
