//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactDimensionMapping
    {
        public int FactDimensionMappingID { get; set; }
        public int FactDimensionSetID { get; set; }
        public int DimensionValueID { get; set; }
    
        public virtual DimensionValue DimensionValue { get; set; }
        public virtual FactDimensionSet FactDimensionSet { get; set; }
    }
}
