//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Geographical_NeedsEntities : DbContext
    {
        public Geographical_NeedsEntities()
            : base("name=Geographical_NeedsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataViewColumn> DataViewColumns { get; set; }
        public virtual DbSet<DataView> DataViews { get; set; }
        public virtual DbSet<Dimension> Dimensions { get; set; }
        public virtual DbSet<DimensionSet> DimensionSets { get; set; }
        public virtual DbSet<DimensionSetCombination> DimensionSetCombinations { get; set; }
        public virtual DbSet<DimensionSetCombinationMember> DimensionSetCombinationMembers { get; set; }
        public virtual DbSet<DimensionSetMember> DimensionSetMembers { get; set; }
        public virtual DbSet<DimensionValue> DimensionValues { get; set; }
        public virtual DbSet<Geography> Geographies { get; set; }
        public virtual DbSet<GeographyType> GeographyTypes { get; set; }
        public virtual DbSet<Measure> Measures { get; set; }
        public virtual DbSet<MeasureBreakdown> MeasureBreakdowns { get; set; }
        public virtual DbSet<StagingColumn> StagingColumns { get; set; }
        public virtual DbSet<StagingDataset> StagingDatasets { get; set; }
        public virtual DbSet<MeasureInstance> MeasureInstances { get; set; }
    }
}
