//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geography
    {
        public Geography()
        {
            this.MeasureInstances = new HashSet<MeasureInstance>();
        }
    
        public int GeographyID { get; set; }
        public Nullable<int> GeographyTypeID { get; set; }
        public string MsoaCode { get; set; }
        public string MsoaName { get; set; }
        public string WardCode { get; set; }
        public string WardName { get; set; }
        public string LsoaCode { get; set; }
        public string LsoaName { get; set; }
        public string Postcode { get; set; }
        public Nullable<double> UPRN { get; set; }
        public Nullable<double> USRN { get; set; }
        public string NAMENUMBER { get; set; }
        public string STREET { get; set; }
        public string LOCATION { get; set; }
        public string TOWN { get; set; }
        public Nullable<decimal> EASTING { get; set; }
        public Nullable<decimal> NORTHING { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SP_GEOMETRY { get; set; }
    
        public virtual GeographyType GeographyType { get; set; }
        public virtual ICollection<MeasureInstance> MeasureInstances { get; set; }
    }
}
