//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeographyType
    {
        public GeographyType()
        {
            this.Facts = new HashSet<Fact>();
            this.Geographies = new HashSet<Geography>();
        }
    
        public int GeographyTypeID { get; set; }
        public string GeographyType1 { get; set; }
        public int OrderInHierarchy { get; set; }
    
        public virtual ICollection<Fact> Facts { get; set; }
        public virtual ICollection<Geography> Geographies { get; set; }
    }
}
