//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSOA
    {
        public LSOA()
        {
            this.FactInstances = new HashSet<FactInstance>();
            this.Properties = new HashSet<Property>();
        }
    
        public int LsoaID { get; set; }
        public string LsoaCode { get; set; }
        public string LsoaName { get; set; }
        public string WardCode { get; set; }
        public string WardName { get; set; }
        public string MsoaCode { get; set; }
        public string MsoaName { get; set; }
        public string CommunityArea { get; set; }
        public string PlanningPolicyArea { get; set; }
        public string LACode { get; set; }
    
        public virtual ICollection<FactInstance> FactInstances { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}
