//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureInstance
    {
        public int MeasureInstanceID { get; set; }
        public int MeasureBreakdownID { get; set; }
        public int DimensionSetCombinationID { get; set; }
        public Nullable<int> GeographyID { get; set; }
        public int Value { get; set; }
        public string LoadReference { get; set; }
    
        public virtual DimensionSetCombination DimensionSetCombination { get; set; }
        public virtual Geography Geography { get; set; }
        public virtual MeasureBreakdown MeasureBreakdown { get; set; }
    }
}
