//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure
    {
        public Measure()
        {
            this.MeasureBreakdowns = new HashSet<MeasureBreakdown>();
        }
    
        public int MeasureID { get; set; }
        public string MeasureName { get; set; }
    
        public virtual ICollection<MeasureBreakdown> MeasureBreakdowns { get; set; }
    }
}
