//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureBreakdown
    {
        public MeasureBreakdown()
        {
            this.MeasureInstances = new HashSet<MeasureInstance>();
        }
    
        public int MeasureBreakdownID { get; set; }
        public string MeasureBreakdownName { get; set; }
        public int MeasureID { get; set; }
        public int DimensionSetID { get; set; }
    
        public virtual DimensionSet DimensionSet { get; set; }
        public virtual Measure Measure { get; set; }
        public virtual ICollection<MeasureInstance> MeasureInstances { get; set; }
    }
}
