//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Loading_Tool.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.FactInstances = new HashSet<FactInstance>();
        }
    
        public int PropertyID { get; set; }
        public Nullable<int> LsoaID { get; set; }
        public string NAMENUMBER { get; set; }
        public string STREET { get; set; }
        public string LOCATION { get; set; }
        public string TOWN { get; set; }
        public double UPRN { get; set; }
        public decimal USRN { get; set; }
        public string POSTCODE { get; set; }
        public decimal EASTING { get; set; }
        public decimal NORTHING { get; set; }
        public double LATITUDE { get; set; }
        public double LONGITUDE { get; set; }
        public System.Data.Spatial.DbGeometry SP_GEOMETRY { get; set; }
    
        public virtual ICollection<FactInstance> FactInstances { get; set; }
        public virtual LSOA LSOA { get; set; }
    }
}
